POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "blaa", 
    "number":"1234", 
    "id": ""
}

###

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "number":"12234", 
    "id": ""
}

###

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "blaaa", 
    "id": ""
}

###